#!/bin/bash

# Install HAProxy
sudo apt update
sudo apt install haproxy -y

# Configure HAProxy
echo "
frontend load-balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

# Enable HAProxy as an init service
sudo systemctl enable haproxy

# Start HAProxy
sudo systemctl start haproxy

# Check HAProxy status
sudo systemctl status haproxy
