#!/bin/bash

# Get a list of active IPv4 addresses
ip_addresses=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1)

# Print each IP address
for ip in $ip_addresses; do
    echo "$ip"
done
