#!/usr/bin/env bash

# Script that listens on port 98 on localhost.
#nc -kl localhost 98
netcat -l localhost 98

# This script listens on port 98 on localhost
#nc -kl localhost 98
netcat -l localhost 98
